# Site settings
title: Strings over Î£
email: blog@bitsrc.org
description: > # this means to ignore newlines until "baseurl:"
  A blog about computer science, logic and programming. Occasionally other topics reasonably consistent with the rest.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http:/bitsrc.org" # the base hostname & protocol for your site
twitter_username: segfaulthunter
github_username:  segfaulthunter

# Build settings
markdown: kramdown
